---
- name: Configure BGP on IOS
  hosts: cisco

  tasks:
    - name: configure global BGP 
      cisco.ios.ios_bgp_global:
        config:
          as_number: 65001
          bgp:
            log_neighbor_changes: true
            router_id:
              address: 192.168.2.2
          neighbor:
            - neighbor_address: 10.200.200.1
              remote_as: 65000  
#              ebgp_multihop:
#                  enable: true
#                  hop_count: 255
    - name: configure address family BGP
      cisco.ios.ios_bgp_address_family:
        config:
          as_number: 65001
          address_family: 
            - afi: ipv4
              neighbor: 
                - address: 10.200.200.1
                  activate: true
              network:
                - address: 10.101.101.0
                  mask: 255.255.255.0
                - address: 10.200.200.0
                  mask: 255.255.255.0
                - address: 172.18.0.0
                - address: 192.168.2.2
                  mask: 255.255.255.255
              redistribute:
                - ospf:
                    process_id: 1
    - name: Verify BGP is running
      cisco.ios.command:
        commands:
          - show ip bgp
          - sh ip bgp neighbor 10.200.200.1
          - sh ip route
  
          
