---
- name: cli command playbook
  hosts: cisco
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: Set boot image
      cisco.ios.ios_config:
        lines: 
        -  no boot system
        -  boot system flash bootflash:{{new_image}}
        host: '{{ inventory_hostname }}'
      when: ansible_net_version != version
    
         

